api.client:
  output: ./api-client
  format: typescript-angular
  formatOptions: supportsES6=true,ngVersion=6.1

sql.model:
  namespace: todo
  user: root
  password: password

rest:
  cors: { active : true }
