files:
  - package.json
  - src
  - resources
  - node_modules/@travetto/cli/bin/travetto.js: node_modules/.bin/trv
  - node_modules/@travetto/cli/bin/travetto.js: node_modules/.bin/travetto
  - lodash/lodash.min.js: lodash/lodash.js
  - '!**/node_modules/@travetto/*/DOCS.js'
  - '!**/node_modules/@travetto/*/alt'
  - '!**/node_modules/@travetto/*/test'
  - '!**/bower.json'
  - '!**/LICENSE'
  - '!*.d.ts'
  - '!*.map'
  - '!*.md'
  - '!*.lock'
  - '!*.html'
  - '!*.mjs'
  - '!test/'
  - '!**/node_modules/lodash/lodash.min.js'
  - '!**/node_modules/typescript/'
  - '!**/node_modules/@types/'  
  - '!**/node_modules/bson/browser_build/'
  - '!**/node_modules/source-map-support/browser-source-map-support.js'