api.spec:
  output: ./openapi.yml

web:
  cors: { active : true }  
  http: 
    tls: true
    httpVersion: 1.1

web.client:
  providers:
    - type: fetch-node
      output: related/todo-app/api-client