api.spec:
  output: ./openapi.yml

rest:
  cors: { active : true }
  ssl: { active: true }

rest.client:
  providers:
    - type: fetch
      output: related/todo-app/api-client
    - type: fetch-web
      output: related/todo-app/resources/ui/js/api-client